### ISSUE TITLE
Fabric + Optifine Crashes the game

### ISSUE THREAD

**Issue by Jpkrus** [izofar/bygone-nether#26]
### Describe the Bug

Whenever I use the fabric version of the mod and use optifine with bygone nether upon trying to start up the game minecraft just crashes and gives me Error code: 1, which means no crash report. I tried optifine and fabric with the "it takes a pillage mod" and it works perfectly fine the only thing that I think that might be breaking is probably one of the mod's mob's.

### Reproduction Steps

1.Install fabric
2.Instal fabric API
3.Instal the fabric version of bygone nether
4.Install Optifine and Optifabric
5.Try booting up Minecraft

### Expected Result

Game crashes giving you Exit code: 1

### Operating System

Windows 10

### Mod Version

1.2.1

### Minecraft Version

1.19.2

### Forge Version

Fabric - 0.14.21

**Comment by zinerith** [comment]
The possibility exists it might be an issue on Optifabric's end, since it's not officially supported by Optifine's developers. There might be no crash report, but if you open the debug log (it's a box you can check in the launcher settings) does it say anything at the end? It might also help to install a debugging mod like https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes

**Comment by izofar** [comment]
Fixed in [eb5881b](https://github.com/izofar/bygone-nether/commit/eb5881bc8fd9d6573a8b8e52827f15bdb2e70922). It was an incompatibility with one of [MidnightLib](https://github.com/TeamMidnightDust/MidnightLib)'s mixins
