### ISSUE TITLE
The advancement "Saving private Swine" is get when summoning an entity like a snowgolem .

### ISSUE THREAD

**Issue by zeid0ne** [izofar/bygone-nether#31]
### Describe the Bug

The advancement "Saving private Swine" is get when summoning an entity like a snowgolem.

### Reproduction Steps

1. Create a new world
2. Summon a snowgolem

### Expected Result

The advancement is not get.

### Screenshots and Videos

![image](https://github.com/izofar/bygone-nether/assets/38461940/d57e3d9c-98f3-406e-8467-9b1ff42ed362)

### Operating System

Windows 10

### Mod Version

1.3.0

### Minecraft Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Other Mods

![image](https://github.com/izofar/bygone-nether/assets/38461940/ecb928a6-7856-4cd3-a7b3-8694b25d9741)

### Additional Context

Thanks for the mod btw.

**Comment by izofar** [comment]
Do you `/summon minecraft:snow_golem` or place the blocks to summon?

**Comment by zeid0ne** [comment]
i place the blocks. It also worked with placing blocks to summon a tuff golem from https://www.curseforge.com/minecraft/mc-mods/what-are-you-voting-for-2022

**Comment by izofar** [comment]
Fixed in [0043317](https://github.com/izofar/bygone-nether/commit/004331724fa3f66bcd26e66709eddc82f3cb1ead) for 1.18.2, [25728fe](https://github.com/izofar/bygone-nether/commit/25728fe5002c9ec731984269ed3564455d51008f) for 1.19.2, and [cb38a20](https://github.com/izofar/bygone-nether/commit/cb38a20bf1ceb2a374f60bdf6994b433b594f54c) for 1.20.x
