### ISSUE TITLE
The audio subtitles are showing unlocalized names.

### ISSUE THREAD

**Issue by Freshah** [izofar/bygone-nether#4]
![2022-04-23_22 33 00](https://user-images.githubusercontent.com/71207812/164953599-c3e398b4-9477-48fa-8377-81a5f5429072.png)

As seen here.  Love the mod

**Comment by izofar** [comment]
Fixed in commits [5dd8b96](https://github.com/izofar/bygone-nether/commit/5dd8b9673d9dc0a682b5885907a25fb9a4cff1aa) (1.18.2), [cf3f032](https://github.com/izofar/bygone-nether/commit/cf3f032091e9ec311e0a2eb4ebf345927d3efde1)(1.18.1), [ee4aab8](https://github.com/izofar/bygone-nether/commit/ee4aab83e3bb6359c8594d248c81218ed15fbeca)(1.16.5)
